#!/bin/bash
# mn_trainer_dense_v36.sh NNODES [BATCH] [MODEL_PATH] [DATA_PATH] [BASETAG]
# =============================================================================
# v36 = clean-start dense RL on the 11-50 mask-complete filtered data from
# StepCount-7B-SFT-1M checkpoint-476, using the merged EasyR1-compatible mask manifest.
# =============================================================================
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${REPO_DIR}/examples/local_path_env.sh"

NNODES="${1:?usage: mn_trainer_dense_v36.sh NNODES [BATCH] [MODEL_PATH] [DATA_PATH] [BASETAG]}"
TOTAL_GPUS=$((NNODES * 8))
if [[ $# -ge 2 ]]; then
  BATCH="${2}"
elif [[ "${TOTAL_GPUS}" -le 8 ]]; then
  BATCH=128
else
  BATCH=256
fi
MODEL_PATH_ARG="${3:-${STEPCOUNT_1M_RESUME_CKPT476_MODEL_PATH}}"
DATA_PATH_ARG="${4:-${STEPCOUNT_DENSE_11_50_MASKCOMPLETE_DATA}}"
BASETAG="${5:-ckpt476_11_50_maskcomplete38332_bokgrpo_h200}"
STEPCOUNT_HARDWARE_PROFILE=${STEPCOUNT_HARDWARE_PROFILE:-h200}
unset NCCL_ASYNC_ERROR_HANDLING
export TORCH_NCCL_ASYNC_ERROR_HANDLING=${TORCH_NCCL_ASYNC_ERROR_HANDLING:-1}

if [[ "${TOTAL_GPUS}" -le 8 ]]; then
  _V36_WRAPPER_MICRO_UPDATE=4
  _V36_WRAPPER_MICRO_EXP=8
  _V36_WRAPPER_GPU_MEM_UTIL=0.55
  _V36_WRAPPER_BATCHED_TOKENS=49152
  _V36_WRAPPER_VLLM_BLOCKS=24576
  _V36_WRAPPER_REWARD_WORKERS=8
  _V36_WRAPPER_MASK_CACHE_MAX=8192
  _V36_WRAPPER_BOK_TOTAL_STEPS=300
  _V36_WRAPPER_SAVE_FREQ=50
else
  _V36_WRAPPER_MICRO_UPDATE=4
  _V36_WRAPPER_MICRO_EXP=8
  _V36_WRAPPER_GPU_MEM_UTIL=0.65
  _V36_WRAPPER_BATCHED_TOKENS=65536
  _V36_WRAPPER_VLLM_BLOCKS=32768
  _V36_WRAPPER_REWARD_WORKERS=16
  _V36_WRAPPER_MASK_CACHE_MAX=4096
  _V36_WRAPPER_BOK_TOTAL_STEPS=150
  _V36_WRAPPER_SAVE_FREQ=75
fi

TS=$(date +%Y%m%d_%H%M)
LOGDIR=${EASYR1_LOG_ROOT}/rl
LOG="${LOGDIR}/v36_${NNODES}node_${BASETAG}_${TS}.log"
mkdir -p "${LOGDIR}"

_ld_parts=()
for _p in /usr/local/nvidia/lib /usr/local/nvidia/lib64 /usr/local/cuda/lib64; do
  [[ -d "${_p}" ]] && _ld_parts+=("${_p}")
done
if [[ ${#_ld_parts[@]} -gt 0 ]]; then
  _ld_prefix="$(IFS=:; echo "${_ld_parts[*]}")"
  export LD_LIBRARY_PATH="${_ld_prefix}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
fi

EXPECT=${TOTAL_GPUS}
GPU=$(ray status 2>/dev/null | grep -oP '(?<=/)[\d.]+(?=\s+GPU)' | head -1)
if [[ "${STEPCOUNT_HARDWARE_PROFILE}" == "h200" ]]; then
  _V36_SOCKET_MODE=${STEPCOUNT_H200_SOCKET_NCCL:-auto}
  _V36_SOCKET_IFNAME=${NCCL_SOCKET_IFNAME:-${STEPCOUNT_NCCL_IFNAME:-}}
  if [[ "${_V36_SOCKET_MODE}" == "auto" && -z "${_V36_SOCKET_IFNAME}" && -d /sys/class/net/brainpf0 ]]; then
    _V36_SOCKET_IFNAME=brainpf0
  fi
  case "${_V36_SOCKET_MODE}" in
    auto)
      [[ -n "${_V36_SOCKET_IFNAME}" ]] && _V36_ENABLE_SOCKET_NCCL=1 || _V36_ENABLE_SOCKET_NCCL=0
      ;;
    1|true|TRUE|yes|YES|on|ON)
      _V36_ENABLE_SOCKET_NCCL=1
      _V36_SOCKET_IFNAME=${_V36_SOCKET_IFNAME:-brainpf0}
      ;;
    0|false|FALSE|no|NO|off|OFF)
      _V36_ENABLE_SOCKET_NCCL=0
      ;;
    *)
      echo "[v36-trainer][ERROR] STEPCOUNT_H200_SOCKET_NCCL must be auto/0/1/true/false, got: ${_V36_SOCKET_MODE}" >&2
      exit 1
      ;;
  esac
  if [[ "${_V36_ENABLE_SOCKET_NCCL}" == "1" ]]; then
    export NCCL_SOCKET_IFNAME=${NCCL_SOCKET_IFNAME:-${_V36_SOCKET_IFNAME}}
    export GLOO_SOCKET_IFNAME=${GLOO_SOCKET_IFNAME:-${NCCL_SOCKET_IFNAME}}
    export NCCL_IB_DISABLE=${NCCL_IB_DISABLE:-1}
  fi
fi
export V36_ENABLE_ULYSSES_SP=${V36_ENABLE_ULYSSES_SP:-0}
case "${V36_ENABLE_ULYSSES_SP}" in
  1|true|TRUE|yes|YES|on|ON)
    if [[ "${V36_ACK_EXPERIMENTAL_VLM_SP:-0}" != "1" || "${V36_ALLOW_UNVALIDATED_QWEN25_VL_SP:-0}" != "1" ]]; then
      echo "[v36-trainer][ERROR] Qwen2.5-VL Ulysses SP is not production-validated." >&2
      echo "Set both V36_ACK_EXPERIMENTAL_VLM_SP=1 and V36_ALLOW_UNVALIDATED_QWEN25_VL_SP=1 only for a short development probe." >&2
      exit 1
    fi
    export V36_ULYSSES_SEQUENCE_PARALLEL_SIZE=${V36_ULYSSES_SEQUENCE_PARALLEL_SIZE:-2}
    export V31_ULYSSES_SEQUENCE_PARALLEL_SIZE=${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE:-${V36_ULYSSES_SEQUENCE_PARALLEL_SIZE}}
    ;;
  0|false|FALSE|no|NO|off|OFF)
    export V31_ULYSSES_SEQUENCE_PARALLEL_SIZE=1
    ;;
  *)
    echo "[v36-trainer][ERROR] V36_ENABLE_ULYSSES_SP must be 0/1/true/false, got: ${V36_ENABLE_ULYSSES_SP}" >&2
    exit 1
    ;;
esac
echo "[v36-trainer] cluster GPUs=${GPU:-?} expected=${EXPECT}"
echo "[v36-trainer] defaults batch=${BATCH} micro=${V31_MICRO_BATCH_UPDATE:-${_V36_WRAPPER_MICRO_UPDATE}}/${V31_MICRO_BATCH_EXP:-${_V36_WRAPPER_MICRO_EXP}} ulysses_enable=${V36_ENABLE_ULYSSES_SP} ulysses_sp=${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE} gpu_mem=${V31_GPU_MEM_UTIL:-${_V36_WRAPPER_GPU_MEM_UTIL}} blocks=${EASYR1_VLLM_NUM_GPU_BLOCKS:-${_V36_WRAPPER_VLLM_BLOCKS}} tokens=${V31_MAX_NUM_BATCHED_TOKENS:-${_V36_WRAPPER_BATCHED_TOKENS}} save_root=${V36_SAVE_ROOT:-${EASYR1_CHECKPOINT_ROOT}}"
echo "[v36-trainer] NCCL_SOCKET_IFNAME=${NCCL_SOCKET_IFNAME:-<cluster-default>} GLOO_SOCKET_IFNAME=${GLOO_SOCKET_IFNAME:-<cluster-default>} NCCL_IB_DISABLE=${NCCL_IB_DISABLE:-<cluster-default>}"
if [[ -n "${GPU:-}" && "${GPU%.*}" != "${EXPECT}" ]]; then
  echo "[v36-trainer][WARN] ray visible GPUs=${GPU}, but NNODES*8=${EXPECT}; check Ray before launch if this is unexpected."
fi
if [[ "${STEPCOUNT_CLEAR_PROXY:-1}" == "1" ]]; then
  unset http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY
  echo "[v36-trainer] proxy env cleared for offline training"
fi

export WANDB_MODE=${WANDB_MODE:-offline}
export WANDB_API_KEY=${WANDB_API_KEY:-}
export WANDB_DIR=${WANDB_DIR:-${EASYR1_LOG_ROOT}/wandb}
export PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
export PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:512,roundup_power2_divisions:16}
export PYTHONHASHSEED=${PYTHONHASHSEED:-0}
export EASYR1_ALLOW_ZERO_MM_LOGPROB=${EASYR1_ALLOW_ZERO_MM_LOGPROB:-0}
export V36_SAVE_ROOT=${V36_SAVE_ROOT:-${EASYR1_CHECKPOINT_ROOT}}
mkdir -p "${WANDB_DIR}"
mkdir -p "${V36_SAVE_ROOT}"

cd "${REPO_DIR}"

setsid nohup env \
  INDEX=0 HOST_NUM="${NNODES}" HOST_GPU_NUM=8 \
  MODEL_PATH="${MODEL_PATH_ARG}" \
  STEPCOUNT_HARDWARE_PROFILE=${STEPCOUNT_HARDWARE_PROFILE} \
  STEPCOUNT_TRAIN_DATA="${DATA_PATH_ARG}" \
  STEPCOUNT_MASKS_METADATA="${STEPCOUNT_DENSE_11_50_MASKS_METADATA}" \
  STEPCOUNT_MASKS_DIR="${STEPCOUNT_DENSE_11_50_MASKS_DIR}" \
  V31_NNODES="${NNODES}" V31_N_GPUS_PER_NODE=8 \
  V31_ROLLOUT_BATCH_SIZE="${BATCH}" V31_GLOBAL_BATCH_SIZE="${BATCH}" V31_VAL_BATCH_SIZE=${V31_VAL_BATCH_SIZE:-${BATCH}} \
  V31_FILTER_OVERLONG_NUM_PROC=${V31_FILTER_OVERLONG_NUM_PROC:-64} EASYR1_FILTER_OVERLONG_NUM_PROC=${EASYR1_FILTER_OVERLONG_NUM_PROC:-${V31_FILTER_OVERLONG_NUM_PROC:-64}} \
  V31_MICRO_BATCH_UPDATE=${V31_MICRO_BATCH_UPDATE:-${_V36_WRAPPER_MICRO_UPDATE}} V31_MICRO_BATCH_EXP=${V31_MICRO_BATCH_EXP:-${_V36_WRAPPER_MICRO_EXP}} V31_GPU_MEM_UTIL=${V31_GPU_MEM_UTIL:-${_V36_WRAPPER_GPU_MEM_UTIL}} \
  V36_ENABLE_ULYSSES_SP=${V36_ENABLE_ULYSSES_SP} V36_ULYSSES_SEQUENCE_PARALLEL_SIZE=${V36_ULYSSES_SEQUENCE_PARALLEL_SIZE:-2} \
  V31_ULYSSES_SEQUENCE_PARALLEL_SIZE=${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE} \
  PYTHONUNBUFFERED="${PYTHONUNBUFFERED}" PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF}" PYTHONHASHSEED="${PYTHONHASHSEED}" \
  EASYR1_VLLM_NUM_GPU_BLOCKS=${EASYR1_VLLM_NUM_GPU_BLOCKS:-${_V36_WRAPPER_VLLM_BLOCKS}} \
  INTERLEAVED_ADAPTIVE_MAX_TURNS=${INTERLEAVED_ADAPTIVE_MAX_TURNS:-true} INTERLEAVED_ADAPTIVE_MAX_TURNS_MARGIN=${INTERLEAVED_ADAPTIVE_MAX_TURNS_MARGIN:-2} INTERLEAVED_POINT_TURN_USE_ANSWER_BUDGET=${INTERLEAVED_POINT_TURN_USE_ANSWER_BUDGET:-true} \
  INTERLEAVED_MAX_TURNS=${INTERLEAVED_MAX_TURNS:-53} INTERLEAVED_PER_TURN_MAX_TOKENS=${INTERLEAVED_PER_TURN_MAX_TOKENS:-512} INTERLEAVED_ANSWER_TURN_MAX_TOKENS=${INTERLEAVED_ANSWER_TURN_MAX_TOKENS:-8192} \
  INTERLEAVED_DEBUG=${INTERLEAVED_DEBUG:-0} INTERLEAVED_DEBUG_PRINT_CHARS=${INTERLEAVED_DEBUG_PRINT_CHARS:-80} \
  V31_MAX_RESPONSE_LENGTH=${V31_MAX_RESPONSE_LENGTH:-16384} V31_MAX_PROMPT_LENGTH=${V31_MAX_PROMPT_LENGTH:-12000} V31_MAX_MODEL_LEN=${V31_MAX_MODEL_LEN:-32768} V31_MAX_NUM_BATCHED_TOKENS=${V31_MAX_NUM_BATCHED_TOKENS:-${_V36_WRAPPER_BATCHED_TOKENS}} V31_ENFORCE_EAGER=${V31_ENFORCE_EAGER:-false} \
  ACTOR_LR=${ACTOR_LR:-1e-6} DISABLE_KL=${DISABLE_KL:-false} USE_KL_LOSS=${USE_KL_LOSS:-false} KL_TYPE=${KL_TYPE:-adaptive} KL_COEF=${KL_COEF:-0.06} \
  KL_TARGET=${KL_TARGET:-0.10} KL_HORIZON=${KL_HORIZON:-50000} KL_PENALTY=${KL_PENALTY:-low_var_kl} ROLLOUT_TEMPERATURE=${ROLLOUT_TEMPERATURE:-0.7} BOK_TOTAL_STEPS=${BOK_TOTAL_STEPS:-${_V36_WRAPPER_BOK_TOTAL_STEPS}} \
  STEPCOUNT_RL_MODE=${STEPCOUNT_RL_MODE:-bok_grpo} ADV_ESTIMATOR=${ADV_ESTIMATOR:-bok_grpo} PROCESS_REWARD_ENABLE=${PROCESS_REWARD_ENABLE:-0} ROLLOUT_N=${ROLLOUT_N:-16} \
  ANSWER_WEIGHT=${ANSWER_WEIGHT:-0.7} POINT_WEIGHT=${POINT_WEIGHT:-0.2} TRAJECTORY_FORMAT_WEIGHT=${TRAJECTORY_FORMAT_WEIGHT:-0.1} \
  TRAJ_FORMAT_STRICT_KEY=${TRAJ_FORMAT_STRICT_KEY:-1} TRAJ_FORMAT_TYPO_CREDIT=${TRAJ_FORMAT_TYPO_CREDIT:-0.0} TRAJ_FORMAT_GRADED=${TRAJ_FORMAT_GRADED:-1} TRAJ_FORMAT_REJECTION=${TRAJ_FORMAT_REJECTION:-structural} TRAJ_POINT_KEY_NORMALIZE=${TRAJ_POINT_KEY_NORMALIZE:-1} \
  TRAJ_ANSWER_GATE_MODE=${TRAJ_ANSWER_GATE_MODE:-soft} TRAJ_SOFT_GATE_BASE=${TRAJ_SOFT_GATE_BASE:-0.7} \
  TRAJ_DENSE_CONTINUOUS_REWARD=${TRAJ_DENSE_CONTINUOUS_REWARD:-1} TRAJ_DENSE_CONTINUOUS_MIN_GT=${TRAJ_DENSE_CONTINUOUS_MIN_GT:-11} \
  TRAJ_DENSE_CONTINUOUS_WRONG_CAP=${TRAJ_DENSE_CONTINUOUS_WRONG_CAP:-0.05} TRAJ_DENSE_CONTINUOUS_WITHIN1_CAP=${TRAJ_DENSE_CONTINUOUS_WITHIN1_CAP:-0.12} \
  TRAJ_COVERAGE_PENALTY_ENABLE=${TRAJ_COVERAGE_PENALTY_ENABLE:-1} TRAJ_COVERAGE_PENALTY_PER_MISS=${TRAJ_COVERAGE_PENALTY_PER_MISS:-0.1} TRAJ_COVERAGE_PENALTY_CAP=${TRAJ_COVERAGE_PENALTY_CAP:-0.3} \
  TRAJ_STOP_NONE_ENABLE=${TRAJ_STOP_NONE_ENABLE:-1} TRAJ_EARLY_STOP_PENALTY=${TRAJ_EARLY_STOP_PENALTY:-0.2} TRAJ_STOP_NONE_BONUS=${TRAJ_STOP_NONE_BONUS:-0.05} \
  TRAJ_STRICT_TRAJECTORY_INTEGRITY=${TRAJ_STRICT_TRAJECTORY_INTEGRITY:-0} TRAJ_STRICT_ANSWER_POINT_CONSISTENCY=${TRAJ_STRICT_ANSWER_POINT_CONSISTENCY:-0} TRAJ_EVAL_REQUIRE_INTEGRITY=${TRAJ_EVAL_REQUIRE_INTEGRITY:-0} \
  TRAJ_HARD_REJECT_TAG_BALANCE=${TRAJ_HARD_REJECT_TAG_BALANCE:-1} TRAJ_HARD_REJECT_COUNT_NUMBER=${TRAJ_HARD_REJECT_COUNT_NUMBER:-0} TRAJ_POINT_COUNT_NUMBER_CHECK=${TRAJ_POINT_COUNT_NUMBER_CHECK:-required} \
  TRAJ_COUNT_NUMBER_FORMAT_WEIGHT=${TRAJ_COUNT_NUMBER_FORMAT_WEIGHT:-0.50} TRAJ_COUNT_NUMBER_POINT_PENALTY_WEIGHT=${TRAJ_COUNT_NUMBER_POINT_PENALTY_WEIGHT:-0.20} \
  POLICY_LOSS_IS_LEVEL=${POLICY_LOSS_IS_LEVEL:-sequence_token} \
  BOK_CLIP=${BOK_CLIP:-4.0} BOK_ALLWRONG_NEG_ONLY=${BOK_ALLWRONG_NEG_ONLY:-1} BOK_ALLWRONG_CAP=${BOK_ALLWRONG_CAP:-0.5} BOK_EASY_THRESHOLD=${BOK_EASY_THRESHOLD:-0.50} BOK_EASY_SCORE_THRESHOLD=${BOK_EASY_SCORE_THRESHOLD:-0.5} \
  BOK_TAU_INIT=${BOK_TAU_INIT:-0.7} BOK_TAU_FINAL=${BOK_TAU_FINAL:-0.4} BOK_SMART_FILTER_THRESHOLD=${BOK_SMART_FILTER_THRESHOLD:-0.955} \
  BOK_DAPO_AUTO_DISABLE_THRESHOLD=${BOK_DAPO_AUTO_DISABLE_THRESHOLD:-0.5} BOK_MIN_BATCH_STD=${BOK_MIN_BATCH_STD:-0.1} BOK_FILTER_ALL_CORRECT=${BOK_FILTER_ALL_CORRECT:-1} BOK_FALLBACK_MODE=${BOK_FALLBACK_MODE:-drgrpo} \
  BOK_STEP_WEIGHT=${BOK_STEP_WEIGHT:-0.0} BOK_PROGRESS_DUP_PENALTY=${BOK_PROGRESS_DUP_PENALTY:-1.0} BOK_STEP_GATE=${BOK_STEP_GATE:-answer_soft} BOK_STEP_MIN_GATE=${BOK_STEP_MIN_GATE:-0.2} \
  REWARD_NUM_WORKERS=${REWARD_NUM_WORKERS:-${_V36_WRAPPER_REWARD_WORKERS}} STEPCOUNT_MASK_CACHE_MAX=${STEPCOUNT_MASK_CACHE_MAX:-${_V36_WRAPPER_MASK_CACHE_MAX}} \
  EASYR1_REWARD_SAMPLE_DEBUG=${EASYR1_REWARD_SAMPLE_DEBUG:-0} EASYR1_REWARD_HEALTH_DEBUG_EVERY=${EASYR1_REWARD_HEALTH_DEBUG_EVERY:-20} EASYR1_REWARD_DEBUG_EVERY=${EASYR1_REWARD_DEBUG_EVERY:-1000} \
  STEPCOUNT_MASK_DEBUG_EVERY=${STEPCOUNT_MASK_DEBUG_EVERY:-1000} STEPCOUNT_TRAJ_REASON_DEBUG_EVERY=${STEPCOUNT_TRAJ_REASON_DEBUG_EVERY:-1000} STEPCOUNT_TRAJ_EVENT_LOG_MAX=${STEPCOUNT_TRAJ_EVENT_LOG_MAX:-20} \
  GRAD_SPIKE_PROTECT=${GRAD_SPIKE_PROTECT:-1} GRAD_SPIKE_THRESHOLD=${GRAD_SPIKE_THRESHOLD:-3.0} GRAD_SPIKE_ABSOLUTE_CAP=${GRAD_SPIKE_ABSOLUTE_CAP:-3.5} \
  GRAD_SPIKE_COOLDOWN=${GRAD_SPIKE_COOLDOWN:-0} GRAD_NONFINITE_COOLDOWN=${GRAD_NONFINITE_COOLDOWN:-0} \
  GRAD_SPIKE_LR_FACTOR=${GRAD_SPIKE_LR_FACTOR:-1.0} GRAD_NONFINITE_LR_FACTOR=${GRAD_NONFINITE_LR_FACTOR:-1.0} \
  GRAD_SPIKE_BRAKE_MAX=${GRAD_SPIKE_BRAKE_MAX:-1000000} GRAD_NONFINITE_BRAKE_MAX=${GRAD_NONFINITE_BRAKE_MAX:-1000000} \
  BOK_DAPO_FILTER=${BOK_DAPO_FILTER:-0} \
  V36_SAVE_ROOT="${V36_SAVE_ROOT}" TRAIN_SAVE_FREQ=${TRAIN_SAVE_FREQ:-${_V36_WRAPPER_SAVE_FREQ}} TRAIN_SAVE_LIMIT=${TRAIN_SAVE_LIMIT:-4} \
  WANDB_MODE="${WANDB_MODE}" WANDB_API_KEY="${WANDB_API_KEY}" WANDB_DIR="${WANDB_DIR}" \
  RAY_worker_register_timeout_seconds=120 \
  bash examples/v36_dense_11_50_full_from_1m_ckpt476.sh > "${LOG}" 2>&1 &
TRAIN_PID=$!
echo "${TRAIN_PID}" > "${LOG}.pid"
(
  tail --pid="${TRAIN_PID}" -f /dev/null >/dev/null 2>&1 || true
  echo "[v36-trainer] TRAIN_PROCESS_EXITED pid=${TRAIN_PID} at $(date '+%F %T %Z')" >> "${LOG}"
) &

sleep 3
echo "[v36-trainer] LAUNCHED NNODES=${NNODES} BATCH=${BATCH} PID=${TRAIN_PID} MODEL=${MODEL_PATH_ARG} DATA=${DATA_PATH_ARG} LOG=${LOG}"
if [[ "${V32_DRY_RUN:-0}" == "1" ]]; then
  wait "${TRAIN_PID}"
  EXIT_CODE=$?
  echo "[v36-trainer] DRY_RUN_EXIT pid=${TRAIN_PID} code=${EXIT_CODE} LOG=${LOG}"
  exit "${EXIT_CODE}"
fi
