#!/bin/bash
# Local path defaults for leo's shared-storage workspace.
# Source this file from launch scripts before setting model/data/mask defaults.

LOCAL_ROOT=${LOCAL_ROOT:-/mnt/shared-storage-user/zhangchenhao}
STEPCOUNT_WORK_ROOT=${STEPCOUNT_WORK_ROOT:-${LOCAL_ROOT}/work/StepcountModel}
STEPCOUNT_DATA_ROOT=${STEPCOUNT_DATA_ROOT:-${STEPCOUNT_WORK_ROOT}/dataset}
STEPCOUNT_MODEL_ROOT=${STEPCOUNT_MODEL_ROOT:-${STEPCOUNT_WORK_ROOT}/model}

if [[ -z "${EASYR1_REPO_ROOT:-}" ]]; then
  EASYR1_REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
EASYR1_LOG_ROOT=${EASYR1_LOG_ROOT:-${EASYR1_REPO_ROOT}/logs}
EASYR1_SAVE_ROOT=${EASYR1_SAVE_ROOT:-${EASYR1_REPO_ROOT}/save}
# Current H200 cluster writes large FSDP checkpoints to the shared model volume.
# Override this single variable when migrating the framework to another cluster.
EASYR1_CHECKPOINT_ROOT=${EASYR1_CHECKPOINT_ROOT:-/mnt/shared-storage-user/puyuan/zhangchenhao/EasyR1-latest/model}
STEPCOUNT_REWARD_FN_PATH=${STEPCOUNT_REWARD_FN_PATH:-${EASYR1_REPO_ROOT}/examples/reward_function/StepCount_mask_reward.py:compute_score}

# Models.
STEPCOUNT_1M_MODEL_PATH=${STEPCOUNT_1M_MODEL_PATH:-${STEPCOUNT_MODEL_ROOT}/StepCount-7B-SFT-1M-merged}
STEPCOUNT_1M_MODEL_FALLBACK=${STEPCOUNT_1M_MODEL_FALLBACK:-${STEPCOUNT_MODEL_ROOT}/StepCount-7B-SFT-1M-resume-from-1963/checkpoint-476}
STEPCOUNT_1M_RESUME_CKPT476_MODEL_PATH=${STEPCOUNT_1M_RESUME_CKPT476_MODEL_PATH:-${STEPCOUNT_MODEL_ROOT}/StepCount-7B-SFT-1M-resume-from-1963/checkpoint-476}
if [[ ! -e "${STEPCOUNT_1M_MODEL_PATH}" && -e "${STEPCOUNT_1M_MODEL_FALLBACK}" ]]; then
  STEPCOUNT_1M_MODEL_PATH="${STEPCOUNT_1M_MODEL_FALLBACK}"
fi
STEPCOUNT_SFT_BASE_MODEL_PATH=${STEPCOUNT_SFT_BASE_MODEL_PATH:-${STEPCOUNT_MODEL_ROOT}/StepCount-7B-SFT-10k-high/checkpoint-1296}

# Datasets.
STEPCOUNT_VAL_DATA=${STEPCOUNT_VAL_DATA:-${STEPCOUNT_DATA_ROOT}/pixmo-test}
STEPCOUNT_STEPCOUNT500_FULL_DATA=${STEPCOUNT_STEPCOUNT500_FULL_DATA:-${STEPCOUNT_DATA_ROOT}/stepcount-500}
STEPCOUNT_STEPCOUNT500_V36_VAL100_DATA=${STEPCOUNT_STEPCOUNT500_V36_VAL100_DATA:-${STEPCOUNT_DATA_ROOT}/stepcount-500-v36-val-100}
STEPCOUNT_REPLAY_DATA=${STEPCOUNT_REPLAY_DATA:-${STEPCOUNT_DATA_ROOT}/StepCountQA-RL-Traj_0_10}
STEPCOUNT_REPLAY_MIXED_DATA=${STEPCOUNT_REPLAY_MIXED_DATA:-${STEPCOUNT_DATA_ROOT}/StepCountQA-RL-Traj_0_10_easy_plus_hard}
STEPCOUNT_DENSE_COMBINED_DATA=${STEPCOUNT_DENSE_COMBINED_DATA:-${STEPCOUNT_DATA_ROOT}/StepCountQA-RL-Traj_11_50_Combined}
STEPCOUNT_DENSE_11_50_FULL_DATA=${STEPCOUNT_DENSE_11_50_FULL_DATA:-${STEPCOUNT_DENSE_COMBINED_DATA}}
STEPCOUNT_DENSE_11_50_MASKCOMPLETE_DATA=${STEPCOUNT_DENSE_11_50_MASKCOMPLETE_DATA:-${STEPCOUNT_DATA_ROOT}/StepCountQA-RL-Traj_11_50_Combined_maskcomplete_38332}
STEPCOUNT_DENSE_11_30_FOCUSED10K_DATA=${STEPCOUNT_DENSE_11_30_FOCUSED10K_DATA:-${STEPCOUNT_DATA_ROOT}/StepCountQA-RL-Traj_11_30_Focused10k_quality_maskcomplete_v36_20260713}
STEPCOUNT_DENSE_11_20_PLUS_REPLAY_DATA=${STEPCOUNT_DENSE_11_20_PLUS_REPLAY_DATA:-${STEPCOUNT_DATA_ROOT}/StepCountQA-RL-Traj_11_20_plus_replay}
if [[ -e "${STEPCOUNT_DENSE_11_20_PLUS_REPLAY_DATA}" ]]; then
  STEPCOUNT_DENSE_TRAIN_DATA_DEFAULT=${STEPCOUNT_DENSE_TRAIN_DATA_DEFAULT:-${STEPCOUNT_DENSE_11_20_PLUS_REPLAY_DATA}}
else
  # Local fallback for path preflight before the curated 11-20+replay set is generated.
  STEPCOUNT_DENSE_TRAIN_DATA_DEFAULT=${STEPCOUNT_DENSE_TRAIN_DATA_DEFAULT:-${STEPCOUNT_DENSE_COMBINED_DATA}}
fi

# Masks used by EasyR1-latest local scripts.
STEPCOUNT_MASKS_METADATA=${STEPCOUNT_MASKS_METADATA:-${LOCAL_ROOT}/StepCount-RL_masks_output/masks_metadata.json}
STEPCOUNT_MASKS_DIR=${STEPCOUNT_MASKS_DIR:-${LOCAL_ROOT}/StepCount-RL_masks_output/masks}
STEPCOUNT_DENSE_11_50_MASKS_METADATA=${STEPCOUNT_DENSE_11_50_MASKS_METADATA:-${STEPCOUNT_DATA_ROOT}/sam_mask/StepCount-RL_masks_output_merged/final_rl_mask_manifest_v36_grouped_missing_remaining12h8_20260705_070420_grouped_progressive_issue_filtered_pointin_quality_upgraded/masks_metadata.easy_r1_compatible.grouped_progressive_issue_filtered.json}
STEPCOUNT_DENSE_11_50_MASKS_DIR=${STEPCOUNT_DENSE_11_50_MASKS_DIR:-${STEPCOUNT_DATA_ROOT}/sam_mask/StepCount-RL_masks_output_merged/masks}

export LOCAL_ROOT STEPCOUNT_WORK_ROOT STEPCOUNT_DATA_ROOT STEPCOUNT_MODEL_ROOT
export EASYR1_REPO_ROOT EASYR1_LOG_ROOT EASYR1_SAVE_ROOT EASYR1_CHECKPOINT_ROOT
export STEPCOUNT_REWARD_FN_PATH
export STEPCOUNT_1M_MODEL_PATH STEPCOUNT_1M_MODEL_FALLBACK STEPCOUNT_1M_RESUME_CKPT476_MODEL_PATH STEPCOUNT_SFT_BASE_MODEL_PATH
export STEPCOUNT_VAL_DATA STEPCOUNT_STEPCOUNT500_FULL_DATA STEPCOUNT_STEPCOUNT500_V36_VAL100_DATA
export STEPCOUNT_REPLAY_DATA STEPCOUNT_REPLAY_MIXED_DATA
export STEPCOUNT_DENSE_COMBINED_DATA STEPCOUNT_DENSE_11_50_FULL_DATA STEPCOUNT_DENSE_11_50_MASKCOMPLETE_DATA
export STEPCOUNT_DENSE_11_30_FOCUSED10K_DATA
export STEPCOUNT_DENSE_11_20_PLUS_REPLAY_DATA STEPCOUNT_DENSE_TRAIN_DATA_DEFAULT
export STEPCOUNT_MASKS_METADATA STEPCOUNT_MASKS_DIR STEPCOUNT_DENSE_11_50_MASKS_METADATA STEPCOUNT_DENSE_11_50_MASKS_DIR
