#!/bin/bash
# ================================================================
# V36 Dense RL (11-50 mask-complete filtered) from StepCount-7B-SFT-1M checkpoint-476.
# ================================================================
# Clean RL start by default:
#   - MODEL_PATH is the SFT checkpoint used to initialize actor weights.
#   - No trainer.load_checkpoint_path is set unless V36_LOAD_CHECKPOINT_PATH is provided.
#   - Stale V32_LOAD_CHECKPOINT_PATH is unset by default.
#
# Launch:
#   bash examples/v36_dense_11_50_full_from_1m_ckpt476.sh
#
# Multi-node wrapper can call this file the same way v35 calls its launcher,
# after exporting INDEX/HOST_NUM/HOST_GPU_NUM/CHIEF_IP.
# ================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/local_path_env.sh"

# ---- Required v36 local assets ----
export PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
export WANDB_MODE=${WANDB_MODE:-offline}
export PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:512,roundup_power2_divisions:16}
export PYTHONHASHSEED=${PYTHONHASHSEED:-0}
export EASYR1_ALLOW_ZERO_MM_LOGPROB=${EASYR1_ALLOW_ZERO_MM_LOGPROB:-0}
export STEPCOUNT_HARDWARE_PROFILE=${STEPCOUNT_HARDWARE_PROFILE:-h200}
unset NCCL_ASYNC_ERROR_HANDLING
export TORCH_NCCL_ASYNC_ERROR_HANDLING=${TORCH_NCCL_ASYNC_ERROR_HANDLING:-1}
export MODEL_PATH=${MODEL_PATH:-${STEPCOUNT_1M_RESUME_CKPT476_MODEL_PATH}}
export STEPCOUNT_TRAIN_DATA=${STEPCOUNT_TRAIN_DATA:-${STEPCOUNT_DENSE_11_50_MASKCOMPLETE_DATA}}
export STEPCOUNT_MASKS_METADATA=${V36_STEPCOUNT_MASKS_METADATA:-${STEPCOUNT_DENSE_11_50_MASKS_METADATA}}
export STEPCOUNT_MASKS_DIR=${V36_STEPCOUNT_MASKS_DIR:-${STEPCOUNT_DENSE_11_50_MASKS_DIR}}
export REWARD_FN_PATH=${REWARD_FN_PATH:-${STEPCOUNT_REWARD_FN_PATH}}
if [[ -z "${STEPCOUNT_VAL_DATA:-}" || "${STEPCOUNT_VAL_DATA}" == "${STEPCOUNT_DATA_ROOT}/pixmo-test" ]]; then
  export STEPCOUNT_VAL_DATA="pixmo-test::${STEPCOUNT_DATA_ROOT}/pixmo-test,stepcount-500-v36-val-100::${STEPCOUNT_STEPCOUNT500_V36_VAL100_DATA}"
fi

# Clean start from MODEL_PATH, unless an explicit v36 resume checkpoint is provided.
if [[ -n "${V36_LOAD_CHECKPOINT_PATH:-}" ]]; then
  export V32_LOAD_CHECKPOINT_PATH="${V36_LOAD_CHECKPOINT_PATH}"
elif [[ "${V36_ALLOW_V32_LOAD_CHECKPOINT:-0}" != "1" ]]; then
  unset V32_LOAD_CHECKPOINT_PATH
fi
if [[ -n "${V36_MAX_STEPS:-}" ]]; then
  export MAX_STEPS="${V36_MAX_STEPS}"
else
  unset MAX_STEPS
fi

# ---- Trainer/data topology defaults (Hydra paths in examples/config.yaml) ----
# Directly running this script targets the currently available single 8xH200 node
# by default. Multi-node wrappers can still override HOST_NUM/V31_NNODES.
export V31_NNODES=${V31_NNODES:-${HOST_NUM:-1}}
export V31_N_GPUS_PER_NODE=${V31_N_GPUS_PER_NODE:-${HOST_GPU_NUM:-8}}
export HOST_NUM=${HOST_NUM:-${V31_NNODES}}
export HOST_GPU_NUM=${HOST_GPU_NUM:-${V31_N_GPUS_PER_NODE}}
_V36_TOTAL_GPUS=$((V31_NNODES * V31_N_GPUS_PER_NODE))
if [[ "${_V36_TOTAL_GPUS}" -le 8 ]]; then
  # 8-GPU H200 profile:
  # - keep ROLLOUT_N=16 for BoK/pass-style exploration quality;
  # - halve prompt groups so per-GPU rollout load matches the previous 16-GPU run;
  # - reduce actor update micro batch and vLLM cache budget to avoid the Step-19
  #   backward OOM observed with micro=8/gpu_mem=0.65.
  _V36_DEFAULT_ROLLOUT_BATCH=128
  _V36_DEFAULT_GLOBAL_BATCH=128
  _V36_DEFAULT_VAL_BATCH=128
  _V36_DEFAULT_FILTER_PROC=64
  _V36_DEFAULT_GPU_MEM_UTIL=0.55
  _V36_DEFAULT_MICRO_UPDATE=4
  _V36_DEFAULT_MICRO_EXP=8
  _V36_DEFAULT_BATCHED_TOKENS=49152
  _V36_DEFAULT_VLLM_BLOCKS=24576
  _V36_DEFAULT_REWARD_WORKERS=8
  _V36_DEFAULT_MASK_CACHE_MAX=8192
  # Keep optimizer/KL semantics tied to the v36 experiment, not to GPU count.
  _V36_DEFAULT_ACTOR_LR=1e-6
  _V36_DEFAULT_KL_COEF=0.06
  _V36_DEFAULT_KL_HORIZON=50000
  _V36_DEFAULT_BOK_TOTAL_STEPS=300
  _V36_DEFAULT_SAVE_FREQ=30
else
  _V36_DEFAULT_ROLLOUT_BATCH=256
  _V36_DEFAULT_GLOBAL_BATCH=256
  _V36_DEFAULT_VAL_BATCH=256
  _V36_DEFAULT_FILTER_PROC=64
  _V36_DEFAULT_GPU_MEM_UTIL=0.65
  _V36_DEFAULT_MICRO_UPDATE=4
  _V36_DEFAULT_MICRO_EXP=8
  _V36_DEFAULT_BATCHED_TOKENS=65536
  _V36_DEFAULT_VLLM_BLOCKS=32768
  _V36_DEFAULT_REWARD_WORKERS=16
  _V36_DEFAULT_MASK_CACHE_MAX=4096
  _V36_DEFAULT_ACTOR_LR=1e-6
  _V36_DEFAULT_KL_COEF=0.06
  _V36_DEFAULT_KL_HORIZON=50000
  _V36_DEFAULT_BOK_TOTAL_STEPS=150
  _V36_DEFAULT_SAVE_FREQ=75
fi
export V31_ROLLOUT_BATCH_SIZE=${V31_ROLLOUT_BATCH_SIZE:-${_V36_DEFAULT_ROLLOUT_BATCH}}
export V31_GLOBAL_BATCH_SIZE=${V31_GLOBAL_BATCH_SIZE:-${V31_ROLLOUT_BATCH_SIZE}}
export V31_VAL_BATCH_SIZE=${V31_VAL_BATCH_SIZE:-${V31_ROLLOUT_BATCH_SIZE}}
export V31_FILTER_OVERLONG_NUM_PROC=${V31_FILTER_OVERLONG_NUM_PROC:-${_V36_DEFAULT_FILTER_PROC}}
export EASYR1_FILTER_OVERLONG_NUM_PROC=${EASYR1_FILTER_OVERLONG_NUM_PROC:-${V31_FILTER_OVERLONG_NUM_PROC}}
export TRAINER_PROJECT_NAME=${TRAINER_PROJECT_NAME:-easy_r1}
export TRAINER_VAL_BEFORE_TRAIN=${TRAINER_VAL_BEFORE_TRAIN:-true}
export TRAINER_VAL_ONLY=${TRAINER_VAL_ONLY:-false}
export TRAINER_VAL_GENERATIONS_TO_LOG=${TRAINER_VAL_GENERATIONS_TO_LOG:-3}

# ---- 11-50 long-chain rollout ----
export INTERLEAVED_ADAPTIVE_MAX_TURNS=${INTERLEAVED_ADAPTIVE_MAX_TURNS:-true}
export INTERLEAVED_ADAPTIVE_MAX_TURNS_MARGIN=${INTERLEAVED_ADAPTIVE_MAX_TURNS_MARGIN:-2}
export INTERLEAVED_MAX_TURNS=${INTERLEAVED_MAX_TURNS:-53}
export INTERLEAVED_POINT_TURN_USE_ANSWER_BUDGET=${INTERLEAVED_POINT_TURN_USE_ANSWER_BUDGET:-true}
export INTERLEAVED_PER_TURN_MAX_TOKENS=${INTERLEAVED_PER_TURN_MAX_TOKENS:-512}
export INTERLEAVED_ANSWER_TURN_MAX_TOKENS=${INTERLEAVED_ANSWER_TURN_MAX_TOKENS:-8192}
export INTERLEAVED_DEBUG=${INTERLEAVED_DEBUG:-0}
export INTERLEAVED_DEBUG_PRINT_CHARS=${INTERLEAVED_DEBUG_PRINT_CHARS:-80}
export V31_MAX_RESPONSE_LENGTH=${V31_MAX_RESPONSE_LENGTH:-16384}
export V31_MAX_PROMPT_LENGTH=${V31_MAX_PROMPT_LENGTH:-12000}
export V31_MAX_MODEL_LEN=${V31_MAX_MODEL_LEN:-32768}
export V31_MAX_NUM_BATCHED_TOKENS=${V31_MAX_NUM_BATCHED_TOKENS:-${_V36_DEFAULT_BATCHED_TOKENS}}
export V31_ENFORCE_EAGER=${V31_ENFORCE_EAGER:-false}
export V31_GPU_MEM_UTIL=${V31_GPU_MEM_UTIL:-${_V36_DEFAULT_GPU_MEM_UTIL}}
export V31_MICRO_BATCH_UPDATE=${V31_MICRO_BATCH_UPDATE:-${_V36_DEFAULT_MICRO_UPDATE}}
export V31_MICRO_BATCH_EXP=${V31_MICRO_BATCH_EXP:-${_V36_DEFAULT_MICRO_EXP}}
export V36_ENABLE_ULYSSES_SP=${V36_ENABLE_ULYSSES_SP:-0}
case "${V36_ENABLE_ULYSSES_SP}" in
  1|true|TRUE|yes|YES|on|ON)
    export V31_ULYSSES_SEQUENCE_PARALLEL_SIZE=${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE:-${V36_ULYSSES_SEQUENCE_PARALLEL_SIZE:-2}}
    ;;
  0|false|FALSE|no|NO|off|OFF)
    export V31_ULYSSES_SEQUENCE_PARALLEL_SIZE=1
    ;;
  *)
    echo "[V36-dense-11-50][ERROR] V36_ENABLE_ULYSSES_SP must be 0/1/true/false, got: ${V36_ENABLE_ULYSSES_SP}" >&2
    exit 1
    ;;
esac
export EASYR1_VLLM_NUM_GPU_BLOCKS=${EASYR1_VLLM_NUM_GPU_BLOCKS:-${_V36_DEFAULT_VLLM_BLOCKS}}
export REWARD_NUM_WORKERS=${REWARD_NUM_WORKERS:-${_V36_DEFAULT_REWARD_WORKERS}}
export STEPCOUNT_MASK_CACHE_MAX=${STEPCOUNT_MASK_CACHE_MAX:-${_V36_DEFAULT_MASK_CACHE_MAX}}
export EASYR1_REWARD_SAMPLE_DEBUG=${EASYR1_REWARD_SAMPLE_DEBUG:-0}
export EASYR1_REWARD_HEALTH_DEBUG_EVERY=${EASYR1_REWARD_HEALTH_DEBUG_EVERY:-20}
export EASYR1_REWARD_DEBUG_EVERY=${EASYR1_REWARD_DEBUG_EVERY:-1000}
export STEPCOUNT_MASK_DEBUG_EVERY=${STEPCOUNT_MASK_DEBUG_EVERY:-1000}
export STEPCOUNT_TRAJ_REASON_DEBUG_EVERY=${STEPCOUNT_TRAJ_REASON_DEBUG_EVERY:-1000}
export STEPCOUNT_TRAJ_EVENT_LOG_MAX=${STEPCOUNT_TRAJ_EVENT_LOG_MAX:-20}

if ! [[ "${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE}" =~ ^[0-9]+$ ]] || [[ "${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE}" -lt 1 ]]; then
  echo "[V36-dense-11-50][ERROR] V31_ULYSSES_SEQUENCE_PARALLEL_SIZE must be a positive integer, got: ${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE}" >&2
  exit 1
fi
if (( _V36_TOTAL_GPUS % V31_ULYSSES_SEQUENCE_PARALLEL_SIZE != 0 )); then
  echo "[V36-dense-11-50][ERROR] total GPUs (${_V36_TOTAL_GPUS}) must be divisible by ulysses SP size (${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE})." >&2
  exit 1
fi
if (( V31_ULYSSES_SEQUENCE_PARALLEL_SIZE > 1 )); then
  if [[ "${V36_ACK_EXPERIMENTAL_VLM_SP:-0}" != "1" || "${V36_ALLOW_UNVALIDATED_QWEN25_VL_SP:-0}" != "1" ]]; then
    echo "[V36-dense-11-50][ERROR] Qwen2.5-VL Ulysses SP is blocked by default because the multimodal mRoPE/image-feature path is not production-validated." >&2
    echo "Set both V36_ACK_EXPERIMENTAL_VLM_SP=1 and V36_ALLOW_UNVALIDATED_QWEN25_VL_SP=1 only for a short development probe." >&2
    exit 1
  fi
  _V36_MODEL_HEADS="$(
    MODEL_PATH="${MODEL_PATH}" python3 - <<'PY' 2>/dev/null || true
import json
import os
from pathlib import Path

config_path = Path(os.environ["MODEL_PATH"]) / "config.json"
if config_path.exists():
    cfg = json.loads(config_path.read_text())
    text_cfg = cfg.get("text_config") or {}
    attn = text_cfg.get("num_attention_heads") or cfg.get("num_attention_heads") or ""
    kv = text_cfg.get("num_key_value_heads") or cfg.get("num_key_value_heads") or ""
    print(f"{attn} {kv}".strip())
PY
  )"
  read -r _V36_MODEL_ATTENTION_HEADS _V36_MODEL_KV_HEADS <<< "${_V36_MODEL_HEADS}"
  if [[ -n "${_V36_MODEL_ATTENTION_HEADS:-}" ]] && (( _V36_MODEL_ATTENTION_HEADS % V31_ULYSSES_SEQUENCE_PARALLEL_SIZE != 0 )); then
    echo "[V36-dense-11-50][ERROR] model attention heads (${_V36_MODEL_ATTENTION_HEADS}) must be divisible by ulysses SP size (${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE})." >&2
    exit 1
  fi
  if [[ -n "${_V36_MODEL_KV_HEADS:-}" ]] && (( _V36_MODEL_KV_HEADS % V31_ULYSSES_SEQUENCE_PARALLEL_SIZE != 0 )); then
    echo "[V36-dense-11-50][ERROR] model KV heads (${_V36_MODEL_KV_HEADS}) must be divisible by ulysses SP size (${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE})." >&2
    exit 1
  fi
fi

# ---- Keep v35 EM-aligned reward, scaled to 11-50 ----
export ANSWER_WEIGHT=${ANSWER_WEIGHT:-0.7}
export POINT_WEIGHT=${POINT_WEIGHT:-0.2}
export TRAJECTORY_FORMAT_WEIGHT=${TRAJECTORY_FORMAT_WEIGHT:-0.1}
export TRAJ_DENSE_CONTINUOUS_REWARD=${TRAJ_DENSE_CONTINUOUS_REWARD:-1}
export TRAJ_DENSE_CONTINUOUS_MIN_GT=${TRAJ_DENSE_CONTINUOUS_MIN_GT:-11}
export TRAJ_DENSE_CONTINUOUS_WRONG_CAP=${TRAJ_DENSE_CONTINUOUS_WRONG_CAP:-0.05}
export TRAJ_DENSE_CONTINUOUS_WITHIN1_CAP=${TRAJ_DENSE_CONTINUOUS_WITHIN1_CAP:-0.12}
export TRAJ_COVERAGE_PENALTY_ENABLE=${TRAJ_COVERAGE_PENALTY_ENABLE:-1}
export TRAJ_COVERAGE_PENALTY_MODE=${TRAJ_COVERAGE_PENALTY_MODE:-mask}
export TRAJ_COVERAGE_PENALTY_PER_MISS=${TRAJ_COVERAGE_PENALTY_PER_MISS:-0.1}
export TRAJ_COVERAGE_PENALTY_CAP=${TRAJ_COVERAGE_PENALTY_CAP:-0.3}
export TRAJ_STOP_NONE_ENABLE=${TRAJ_STOP_NONE_ENABLE:-1}
export TRAJ_EARLY_STOP_PENALTY=${TRAJ_EARLY_STOP_PENALTY:-0.2}
export TRAJ_STOP_NONE_BONUS=${TRAJ_STOP_NONE_BONUS:-0.05}
export TRAJ_RETURN_POINT_STEP_SCORES=${TRAJ_RETURN_POINT_STEP_SCORES:-1}
export TRAJ_EXTRA_POINT_PENALTY_LAMBDA=${TRAJ_EXTRA_POINT_PENALTY_LAMBDA:-1.0}
export TRAJ_STRICT_TRAJECTORY_INTEGRITY=${TRAJ_STRICT_TRAJECTORY_INTEGRITY:-0}
export TRAJ_STRICT_ANSWER_POINT_CONSISTENCY=${TRAJ_STRICT_ANSWER_POINT_CONSISTENCY:-0}
export TRAJ_EVAL_REQUIRE_INTEGRITY=${TRAJ_EVAL_REQUIRE_INTEGRITY:-0}
export TRAJ_HARD_REJECT_TAG_BALANCE=${TRAJ_HARD_REJECT_TAG_BALANCE:-1}
export TRAJ_HARD_REJECT_COUNT_NUMBER=${TRAJ_HARD_REJECT_COUNT_NUMBER:-0}
export TRAJ_POINT_COUNT_NUMBER_CHECK=${TRAJ_POINT_COUNT_NUMBER_CHECK:-required}
export TRAJ_COUNT_NUMBER_FORMAT_WEIGHT=${TRAJ_COUNT_NUMBER_FORMAT_WEIGHT:-0.50}
export TRAJ_COUNT_NUMBER_POINT_PENALTY_WEIGHT=${TRAJ_COUNT_NUMBER_POINT_PENALTY_WEIGHT:-0.20}
export TRAJ_ANSWER_GATE_MODE=${TRAJ_ANSWER_GATE_MODE:-soft}
export TRAJ_SOFT_GATE_BASE=${TRAJ_SOFT_GATE_BASE:-0.7}

# ---- Format strict-key and tolerant parser ----
export TRAJ_FORMAT_STRICT_KEY=${TRAJ_FORMAT_STRICT_KEY:-1}
export TRAJ_FORMAT_TYPO_CREDIT=${TRAJ_FORMAT_TYPO_CREDIT:-0.0}
export TRAJ_FORMAT_GRADED=${TRAJ_FORMAT_GRADED:-1}
export TRAJ_FORMAT_REJECTION=${TRAJ_FORMAT_REJECTION:-structural}
export TRAJ_POINT_KEY_NORMALIZE=${TRAJ_POINT_KEY_NORMALIZE:-1}

# ---- BoK/optimization defaults for clean dense 11-50 run ----
export STEPCOUNT_RL_MODE=${STEPCOUNT_RL_MODE:-bok_grpo}
export ADV_ESTIMATOR=${ADV_ESTIMATOR:-bok_grpo}
export PROCESS_REWARD_ENABLE=${PROCESS_REWARD_ENABLE:-0}
export ROLLOUT_N=${ROLLOUT_N:-16}
export ROLLOUT_TEMPERATURE=${ROLLOUT_TEMPERATURE:-0.7}
export ACTOR_LR=${ACTOR_LR:-${_V36_DEFAULT_ACTOR_LR}}
export DISABLE_KL=${DISABLE_KL:-false}
export USE_KL_LOSS=${USE_KL_LOSS:-false}
export KL_TYPE=${KL_TYPE:-adaptive}
export KL_COEF=${KL_COEF:-${_V36_DEFAULT_KL_COEF}}
export KL_TARGET=${KL_TARGET:-0.10}
export KL_HORIZON=${KL_HORIZON:-${_V36_DEFAULT_KL_HORIZON}}
export KL_PENALTY=${KL_PENALTY:-low_var_kl}
export BOK_CLIP=${BOK_CLIP:-4.0}
export BOK_TAU_INIT=${BOK_TAU_INIT:-0.7}
export BOK_TAU_FINAL=${BOK_TAU_FINAL:-0.4}
export BOK_EASY_THRESHOLD=${BOK_EASY_THRESHOLD:-0.50}
export BOK_SMART_FILTER_THRESHOLD=${BOK_SMART_FILTER_THRESHOLD:-0.955}
export BOK_STEP_WEIGHT=${BOK_STEP_WEIGHT:-0.0}
export BOK_PROGRESS_DUP_PENALTY=${BOK_PROGRESS_DUP_PENALTY:-1.0}
export BOK_STEP_GATE=${BOK_STEP_GATE:-answer_soft}
export BOK_STEP_MIN_GATE=${BOK_STEP_MIN_GATE:-0.2}
export BOK_ALLWRONG_NEG_ONLY=${BOK_ALLWRONG_NEG_ONLY:-1}
export BOK_ALLWRONG_CAP=${BOK_ALLWRONG_CAP:-0.5}
export BOK_DAPO_FILTER=${BOK_DAPO_FILTER:-0}
export BOK_DAPO_AUTO_DISABLE_THRESHOLD=${BOK_DAPO_AUTO_DISABLE_THRESHOLD:-0.5}
export BOK_MIN_BATCH_STD=${BOK_MIN_BATCH_STD:-0.1}
export BOK_EASY_SCORE_THRESHOLD=${BOK_EASY_SCORE_THRESHOLD:-0.5}
export BOK_FILTER_ALL_CORRECT=${BOK_FILTER_ALL_CORRECT:-1}
export BOK_FALLBACK_MODE=${BOK_FALLBACK_MODE:-drgrpo}
export POLICY_LOSS_IS_LEVEL=${POLICY_LOSS_IS_LEVEL:-sequence_token}

# Trainer computes real total_steps from dataloader; this is only a fallback.
export BOK_TOTAL_STEPS=${BOK_TOTAL_STEPS:-${_V36_DEFAULT_BOK_TOTAL_STEPS}}

# ---- Grad-safety: skip unsafe updates, do not modify LR automatically ----
export GRAD_SPIKE_PROTECT=${GRAD_SPIKE_PROTECT:-1}
export GRAD_SPIKE_THRESHOLD=${GRAD_SPIKE_THRESHOLD:-3.0}
export GRAD_SPIKE_ABSOLUTE_CAP=${GRAD_SPIKE_ABSOLUTE_CAP:-3.5}
export GRAD_SPIKE_COOLDOWN=${GRAD_SPIKE_COOLDOWN:-0}
export GRAD_NONFINITE_COOLDOWN=${GRAD_NONFINITE_COOLDOWN:-0}
export GRAD_SPIKE_LR_FACTOR=${GRAD_SPIKE_LR_FACTOR:-1.0}
export GRAD_NONFINITE_LR_FACTOR=${GRAD_NONFINITE_LR_FACTOR:-1.0}
export GRAD_SPIKE_BRAKE_MAX=${GRAD_SPIKE_BRAKE_MAX:-1000000}
export GRAD_NONFINITE_BRAKE_MAX=${GRAD_NONFINITE_BRAKE_MAX:-1000000}

# ---- Checkpoint/log identity ----
export TRAIN_SAVE_FREQ=${TRAIN_SAVE_FREQ:-${_V36_DEFAULT_SAVE_FREQ}}
export TRAIN_SAVE_LIMIT=${TRAIN_SAVE_LIMIT:-3}
export TRAIN_VAL_FREQ=${TRAIN_VAL_FREQ:-30}
export V31_EXPERIMENT_NAME=${V31_EXPERIMENT_NAME:-StepCount-7B_v36_dense_11_50_maskcomplete38332_ckpt476_${_V36_TOTAL_GPUS}gpu_$(date +%Y%m%d_%H%M)}
export V36_SAVE_ROOT=${V36_SAVE_ROOT:-${EASYR1_CHECKPOINT_ROOT}}
mkdir -p "${V36_SAVE_ROOT}"
export V31_SAVE_CHECKPOINT_PATH=${V31_SAVE_CHECKPOINT_PATH:-${V36_SAVE_ROOT}/${V31_EXPERIMENT_NAME}}
mkdir -p "${V31_SAVE_CHECKPOINT_PATH}"

# Persist the dataset and topology identity beside global_step_* so resume does
# not have to infer critical state from a user-editable experiment name.
_V36_RUN_MANIFEST="${V31_SAVE_CHECKPOINT_PATH}/v36_run_manifest.tsv"
_V36_RUN_MANIFEST_TMP="${_V36_RUN_MANIFEST}.tmp.$$"
{
  printf 'manifest_version\t1\n'
  printf 'STEPCOUNT_TRAIN_DATA\t%s\n' "${STEPCOUNT_TRAIN_DATA}"
  printf 'MODEL_PATH\t%s\n' "${MODEL_PATH}"
  printf 'STEPCOUNT_MASKS_METADATA\t%s\n' "${STEPCOUNT_MASKS_METADATA}"
  printf 'STEPCOUNT_MASKS_DIR\t%s\n' "${STEPCOUNT_MASKS_DIR}"
  printf 'V31_EXPERIMENT_NAME\t%s\n' "${V31_EXPERIMENT_NAME}"
  printf 'TOTAL_GPUS\t%s\n' "${_V36_TOTAL_GPUS}"
  printf 'ROLLOUT_N\t%s\n' "${ROLLOUT_N}"
  printf 'ADV_ESTIMATOR\t%s\n' "${ADV_ESTIMATOR}"
  printf 'created_at\t%s\n' "$(date '+%F %T %Z')"
} > "${_V36_RUN_MANIFEST_TMP}"
mv -f "${_V36_RUN_MANIFEST_TMP}" "${_V36_RUN_MANIFEST}"

echo "================================================================"
echo "[V36-dense-11-50] clean_start=1 model=${MODEL_PATH}"
echo "[V36-dense-11-50] hardware_profile=${STEPCOUNT_HARDWARE_PROFILE}"
echo "[V36-dense-11-50] runtime wandb=${WANDB_MODE} alloc=${PYTORCH_CUDA_ALLOC_CONF} seed=${PYTHONHASHSEED}"
echo "[V36-dense-11-50] data=${STEPCOUNT_TRAIN_DATA}"
echo "[V36-dense-11-50] val=${STEPCOUNT_VAL_DATA}"
echo "[V36-dense-11-50] masks_meta=${STEPCOUNT_MASKS_METADATA}"
echo "[V36-dense-11-50] masks_dir=${STEPCOUNT_MASKS_DIR}"
echo "[V36-dense-11-50] nnodes=${V31_NNODES} gpus_per_node=${V31_N_GPUS_PER_NODE} rollout_batch=${V31_ROLLOUT_BATCH_SIZE} global_batch=${V31_GLOBAL_BATCH_SIZE} val_batch=${V31_VAL_BATCH_SIZE} filter_num_proc=${V31_FILTER_OVERLONG_NUM_PROC}"
echo "[V36-dense-11-50] turns=${INTERLEAVED_MAX_TURNS} adaptive=${INTERLEAVED_ADAPTIVE_MAX_TURNS} margin=${INTERLEAVED_ADAPTIVE_MAX_TURNS_MARGIN} point_answer_budget=${INTERLEAVED_POINT_TURN_USE_ANSWER_BUDGET} point_tokens=${INTERLEAVED_PER_TURN_MAX_TOKENS} answer_tokens=${INTERLEAVED_ANSWER_TURN_MAX_TOKENS}"
echo "[V36-dense-11-50] prompt_len=${V31_MAX_PROMPT_LENGTH} response_len=${V31_MAX_RESPONSE_LENGTH} model_len=${V31_MAX_MODEL_LEN} batched_tokens=${V31_MAX_NUM_BATCHED_TOKENS} blocks=${EASYR1_VLLM_NUM_GPU_BLOCKS} enforce_eager=${V31_ENFORCE_EAGER}"
echo "[V36-dense-11-50] reward w=${ANSWER_WEIGHT}/${POINT_WEIGHT}/${TRAJECTORY_FORMAT_WEIGHT} wrong_cap=${TRAJ_DENSE_CONTINUOUS_WRONG_CAP} within1=${TRAJ_DENSE_CONTINUOUS_WITHIN1_CAP}"
echo "[V36-dense-11-50] adv=${ADV_ESTIMATOR} process_reward=${PROCESS_REWARD_ENABLE} kl=${KL_COEF} kl_type=${KL_TYPE} use_kl_loss=${USE_KL_LOSS} target=${KL_TARGET} horizon=${KL_HORIZON}"
echo "[V36-dense-11-50] rollout_n=${ROLLOUT_N} temp=${ROLLOUT_TEMPERATURE} lr=${ACTOR_LR} gpu_mem=${V31_GPU_MEM_UTIL} micro=${V31_MICRO_BATCH_UPDATE}/${V31_MICRO_BATCH_EXP} ulysses_enable=${V36_ENABLE_ULYSSES_SP} ulysses_sp=${V31_ULYSSES_SEQUENCE_PARALLEL_SIZE} reward_workers=${REWARD_NUM_WORKERS} mask_cache_max=${STEPCOUNT_MASK_CACHE_MAX}"
echo "[V36-dense-11-50] gate=${TRAJ_ANSWER_GATE_MODE} soft_base=${TRAJ_SOFT_GATE_BASE} bok_tau=${BOK_TAU_INIT}->${BOK_TAU_FINAL} smart_filter=${BOK_SMART_FILTER_THRESHOLD} bok_step_weight=${BOK_STEP_WEIGHT}"
echo "[V36-dense-11-50] trainer project=${TRAINER_PROJECT_NAME} val_before_train=${TRAINER_VAL_BEFORE_TRAIN} val_only=${TRAINER_VAL_ONLY} val_log=${TRAINER_VAL_GENERATIONS_TO_LOG} save_freq=${TRAIN_SAVE_FREQ} val_freq=${TRAIN_VAL_FREQ}"
echo "[V36-dense-11-50] save=${V31_SAVE_CHECKPOINT_PATH}"
echo "[V36-dense-11-50] load=${V32_LOAD_CHECKPOINT_PATH:-<clean-start>}"
echo "[V36-dense-11-50] max_steps=${MAX_STEPS:-<full-epoch>}"
echo "================================================================"

exec bash "${SCRIPT_DIR}/v32_sparse_0_10_stable_drfix.sh"
